# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LanTrans.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LanTrans(object):
    def setupUi(self, LanTrans):
        LanTrans.setObjectName("LanTrans")
        LanTrans.setEnabled(True)
        LanTrans.setFixedSize(689, 497)
        self.centralwidget = QtWidgets.QWidget(LanTrans)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(511, 45, 151, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.receiveFileLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.receiveFileLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.receiveFileLayout.setObjectName("receiveFileLayout")
        self.sendFileRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sendFileRadio.setChecked(True)
        self.sendFileRadio.setObjectName("sendFileRadio")
        self.receiveFileLayout.addWidget(self.sendFileRadio)
        self.addFileBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addFileBtn.setObjectName("addFileBtn")
        self.receiveFileLayout.addWidget(self.addFileBtn)
        self.removeBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.removeBtn.setObjectName("removeBtn")
        self.receiveFileLayout.addWidget(self.removeBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.receiveFileLayout.addItem(spacerItem)
        self.receiveFileRadio = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.receiveFileRadio.setObjectName("receiveFileRadio")
        self.receiveFileLayout.addWidget(self.receiveFileRadio)
        self.savePathBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.savePathBtn.setObjectName("savePathBtn")
        self.receiveFileLayout.addWidget(self.savePathBtn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 471, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.statusLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.statusLayout.setObjectName("statusLayout")
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.status.setObjectName("status")
        self.statusLayout.addWidget(self.status)
        self.statusText = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.statusText.setObjectName("statusText")
        self.statusLayout.addWidget(self.statusText)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(29, 209, 471, 241))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.processdureLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.processdureLayout.setObjectName("processdureLayout")
        self.processdure = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.processdure.setObjectName("processdure")
        self.processdureLayout.addWidget(self.processdure)
        self.fileList = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.fileList.setObjectName("fileList")
        self.processdureLayout.addWidget(self.fileList)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(510, 370, 151, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.actionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.actionLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.actionLayout.setObjectName("actionLayout")
        self.connectHostBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.connectHostBtn.setObjectName("connectHostBtn")
        self.actionLayout.addWidget(self.connectHostBtn)
        self.startBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.startBtn.setObjectName("startBtn")
        self.actionLayout.addWidget(self.startBtn)
        LanTrans.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LanTrans)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        LanTrans.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LanTrans)
        self.statusbar.setObjectName("statusbar")
        LanTrans.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(LanTrans)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(LanTrans)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(LanTrans)
        QtCore.QMetaObject.connectSlotsByName(LanTrans)

    def retranslateUi(self, LanTrans):
        _translate = QtCore.QCoreApplication.translate
        LanTrans.setWindowTitle(_translate("LanTrans", "LanTrans"))
        self.sendFileRadio.setText(_translate("LanTrans", "发送文件"))
        self.addFileBtn.setText(_translate("LanTrans", "添加"))
        self.removeBtn.setText(_translate("LanTrans", "移除"))
        self.receiveFileRadio.setText(_translate("LanTrans", "接收文件"))
        self.savePathBtn.setText(_translate("LanTrans", "保存位置"))
        self.status.setText(_translate("LanTrans", "状态"))
        self.processdure.setText(_translate("LanTrans", "进度"))
        self.connectHostBtn.setText(_translate("LanTrans", "连接主机"))
        self.startBtn.setText(_translate("LanTrans", "开始"))
        self.menuFile.setTitle(_translate("LanTrans", "文件"))
        self.menuAbout.setTitle(_translate("LanTrans", "帮助"))
        self.actionExit.setText(_translate("LanTrans", "退出"))
        self.actionAbout.setText(_translate("LanTrans", "关于"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LanTrans = QtWidgets.QMainWindow()
    ui = Ui_LanTrans()
    ui.setupUi(LanTrans)
    LanTrans.show()
    sys.exit(app.exec_())

